# Generated by Django 4.2.1 on 2023-07-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='data created')),
                ('image', models.ImageField(blank=True, upload_to='media/image', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
