# Generated by Django 4.2.1 on 2023-07-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='data_created')),
                ('data_modified', models.DateTimeField(auto_now=True, verbose_name='data_modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_name', to='pages.package', verbose_name='package_name')),
            ],
        ),
    ]
