# Generated by Django 4.2.1 on 2023-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='image'),
        ),
    ]
