# Generated by Django 4.2.1 on 2024-02-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(max_length='255', verbose_name='user message')),
                ('admin_text', models.TextField(blank=True, max_length='255', verbose_name='admin message')),
                ('is_new', models.BooleanField(default=True, verbose_name='new')),
                ('user_sent_date_time', models.TimeField(auto_now_add=True, verbose_name='send at')),
                ('admin_sent_date_time', models.TimeField(auto_now=True, verbose_name='answers at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactus', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contacts Us',
            },
        ),
    ]
