# Generated by Django 4.2.1 on 2023-09-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='datetime_admin_created',
            field=models.TimeField(auto_now=True, verbose_name='datetime_admin_created'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='is_new'),
        ),
    ]
