# Generated by Django 4.2.1 on 2024-01-20 22:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_sent', models.DateTimeField(auto_now_add=True, verbose_name='send date time')),
                ('date_time_seen', models.DateTimeField(auto_now=True, verbose_name='seen date time')),
                ('sender', models.CharField(max_length=50, verbose_name='sender')),
                ('subject', models.CharField(max_length=300, verbose_name='subject')),
                ('access_way', models.CharField(max_length=100, verbose_name='access way')),
                ('is_checked', models.BooleanField(default=False, verbose_name='is checked ?')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.ImageField(blank=True, upload_to='image/products_image', verbose_name='Image')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('is_offer', models.BooleanField(default=False, verbose_name='Offer')),
                ('offer_percent', models.PositiveIntegerField(default=0, verbose_name='Offer Percent')),
                ('show', models.BooleanField(default=False, verbose_name='Show')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'verbose_name': 'PRODUCT',
                'verbose_name_plural': 'PRODUCTS',
            },
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('reply_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL, verbose_name='reply author')),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='shop.comment', verbose_name='reply comment ')),
                ('reply_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='shop.product', verbose_name='reply product')),
            ],
            options={
                'verbose_name': 'ReplyComment',
                'verbose_name_plural': 'ReplyComments',
            },
        ),
        migrations.CreateModel(
            name='ProductColorSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=8, verbose_name='Product Size')),
                ('color_1', models.CharField(max_length=30, verbose_name='color 1')),
                ('how_many_color_1', models.PositiveIntegerField(default=0, verbose_name='How many color 1')),
                ('color_2', models.CharField(blank=True, max_length=30, verbose_name='color 2')),
                ('how_many_color_2', models.PositiveIntegerField(default=0, verbose_name='How many color 2')),
                ('color_3', models.CharField(blank=True, max_length=30, verbose_name='color 3')),
                ('how_many_color_3', models.PositiveIntegerField(default=0, verbose_name='How many color 3')),
                ('color_4', models.CharField(blank=True, max_length=100, verbose_name='color 4')),
                ('how_many_color_4', models.PositiveIntegerField(default=0, verbose_name='How many 4')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_color_count', to='shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': "product's Size AND Color",
                'verbose_name_plural': 'Products Size And Color  ',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='product'),
        ),
    ]
