# Generated by Django 4.2.1 on 2024-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorsizecount',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L')], max_length=8, verbose_name='Product Size'),
        ),
    ]
