# Generated by Django 4.2.1 on 2024-01-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productcolorsizecount_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorsizecount',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=8, verbose_name='Product Size'),
        ),
    ]
