# Generated by Django 4.2.1 on 2024-02-10 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_productcolorsizecount_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),

                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('phone_number', models.PositiveIntegerField(verbose_name='Phone Number')),
                ('address', models.CharField(max_length=600, verbose_name='Address')),
                ('order_notes', models.CharField(blank=True, max_length=700, verbose_name='Order Notes')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal Authority')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=150, verbose_name='Zarinpal Ref Id')),
                ('zarinpal_data', models.TextField(blank=True, verbose_name='Zarinpal Data')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('size', models.CharField(max_length=20, verbose_name='Size')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order',
                                   verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_items',
                                              to='shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
