# Generated by Django 4.2.1 on 2023-10-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارشات', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ایتم های سفارش', 'verbose_name_plural': 'ایتم های سفارش'},
        ),
    ]
